# Generated by Django 4.2.1 on 2023-11-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('golf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='golfer',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='golfer_profile_pic/'),
        ),
    ]
